#!/bin/sh /etc/rc.common

START=200
start() {
    lsmod | grep -q vizzini || insmod /lib/vizzini.ko
    if [ -z `pidof server485` ] ;then
        [ -e /root/server485 ] && sleep 10 && /root/server485 -d -s -p 8000 -t /dev/ttyUSB2 /dev/ttyUSB0
    fi

    if [ -z `pidof daemon.sh` ] ;then
        [ -e /root/daemon.sh ] && /root/daemon.sh &
    fi
}

stop()
{
    kill -9 `pidof daemon.sh` 2>/dev/null
    kill -9 `pidof server485` 2>/dev/null
}
