#!/usr/bin/env python
# -*- coding: utf-8 -*-
import xmlrpclib  
import time

server = xmlrpclib.ServerProxy("http://192.168.2.100:8001/RPC2")

print server.get_version()
print server.query_env()
#server.set_env((1, 2, 3, 1, 2, 3, 8000, 0))

#server.system.shutdown("ok")
